### ISSUE TITLE
CodeLens not discovering tests with TestCase attributes - Test Explorer can see them

### ISSUE THREAD

**Issue by JohnLudlow** [nunit/nunit-vs-adapter#105] opened 2016-04-19 17:54 UTC
NUnit Version : 3.2.0.0           
     NUnit Source : Nuget
     Visual Studio Version : Visual Studio 2015 Enterprise

I have some tests with [TestCase] attributes. The Test Explorer shows them as expected, with a row for each case. However, when I navigate to one of these tests, I saw that it doesn't have the normal indicator in CodeLens.

Test in Test Explorer:
![image](https://cloud.githubusercontent.com/assets/1769289/14649412/be4bbed6-065e-11e6-82ef-a7b744c59450.png)

Test in code, sans CodeLens indicator:
![image](https://cloud.githubusercontent.com/assets/1769289/14649419/c8800880-065e-11e6-974e-d970a826ff57.png)

I noticed that another test did have the correct indicator:

![image](https://cloud.githubusercontent.com/assets/1769289/14649455/f7b4f476-065e-11e6-9fa3-0dc80a059984.png)

This test does not use the TestCase attributes.

If I alter the affected tests to not use TestCases then CodeLens works (though a large part of the reason we are using NUnit for this project is because of the TestCase support!)

Let me know if more information or a sample project is required.

Thanks

**Comment by rprouse** [comment] 2016-04-19 18:24
This is a duplicate of nunit/nunit3-vs-adapter#55 reported against the NUnit 3 adapter. That issue was closed because it is a limitation/bug in code lens not supporting data driven tests, I believe because MSTest does not. NUnit does not have control over that feature, we just supply the information to Visual Studio. I am going to close this issue as not our bug, sorry.

**Closed by rprouse** 2016-04-19 18:24 UTC

**Comment by JohnLudlow** [comment] 2016-04-19 22:45
Hmmm, guess I missed that when I took a search through your issues.

I guess if it's not your bug then it's not your bug. I kind of half expected this, but when I found some posts saying that CodeLens just uses the same stuff as Test Explorer, it sounded like this was supposed to work.

Maybe I'll see if there's anything on UserVoice.

Thanks!

**Comment by rprouse** [comment] 2016-04-19 23:55
@JohnLudlow if you find anything to the contrary, let us know. This is one of those issues we are aware of, comes up often and would like to fix. If there is anything we can do to fix it, we will :smile:

**Comment by JohnLudlow** [comment] 2016-04-20 12:02
I've reported it via the Report A Problem tool. I'll let you know if I see any sort of response.

Thanks

**Comment by tparikka** [comment] 2017-03-23 14:37
If anyone still watching this issue wants to raise this to Microsoft, I've added a Uservoice request for it at the request of Microsoft's social media team as they told me they had no previous requests for this enhancement.

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/18701998-codelens-doesn-t-detect-parameterized-nunit-tests
