### ISSUE TITLE
NUnit v3 not running tests with AutoFixture.NUnit3.AutoData attribute

### ISSUE THREAD

**Issue by UnderHeavyDevelopment** [nunit/nunit-vs-adapter#157] opened 2017-07-11 09:39 UTC
Tests marked with **[AutoData] attribute** are not run by NUnit test runner.

Platform: **.NET Framework 4.6.1**
Required nugets:
- AutoFixture v3.50.2
- AutoFixture.NUnit3 v3.50.2
- NUnit v3.7.1

Example:

```csharp
using System;
using NUnit.Framework;
using Ploeh.AutoFixture;
using Ploeh.AutoFixture.NUnit3;

[TestFixture]
public class Tests
{
    [Test]
    [AutoData] // without this and argument it works
    public void AutoDataTest(int counter)
    {
        string result = counter.ToString();
        Assert.IsNotNull(result);
    }
}
```

Such test:
- does not run when clicking Run Test
- does not run when executing Run All
- **is discovered** (!), means is displayed in **Test Explorer** window, but under **Not Run Tests** always.
- is shown on test list WITH dummy argument generated by AutoData, like: **AutoDataTest(3)**

**Comment by ChrisMaddock** [comment] 2017-07-11 09:44
I believe this is a duplicate of https://github.com/nunit/nunit3-vs-adapter/issues/342

Closing - let me know if I've missed something and should reopen!

**Closed by ChrisMaddock** 2017-07-11 09:44 UTC
