### ISSUE TITLE
test class grouping broken when using inheritance

### ISSUE THREAD

**Issue by GoppeltM** [nunit/nunit-vs-adapter#19] opened 2013-11-06 13:49 UTC
Tested with Test Adapter Release 1.0
Since VS2012 Update 2, you can also group unit tests via Class name. However, when using inheritance, sub classes are grouped via their parent name.
Example:
class Parent
   <Test> Sub DoSth()
End Class
Class Child
   inherits Parent
End Class
DoSth() will turn up two times in the test explorer - in two categories, both called "Parent".
This might or might not be related: TestContext.CurrentContext.Test.FullName returns
"Namespace.Parent.DoSth" for the parent class method, and "Namespace.Child.Parent.DoSth" for the child class. I guess the class hierarchy should be inverted.

**Comment by CharliePoole** [comment] 2015-12-01 23:00
@OsirisTerje Since this is caused by an issue in NUnit V2, I'm inclined to close this as not (our) bug. It will never be fixed in NUnit.

For 3.0, the behavior is entirely different so this particular bug can't arise.

What do you think?

**Comment by OsirisTerje** [comment] 2016-07-14 20:14
Closed as 3.0 is now out.

**Closed by OsirisTerje** 2016-07-14 20:14 UTC
