### ISSUE TITLE
Nunit 2 test adapter does not support Visual Studio 2019

### ISSUE THREAD

**Issue by bkilada** [nunit/nunit-vs-adapter#180] opened 2019-04-05 18:16 UTC
The NUnit 2 test adapter doesn't support Visual Studio 2019, which was released a few days ago. Are there any plans implement support?

Thanks,
Ben

**Comment by OsirisTerje** [comment] 2019-04-05 19:43
It is supported by the nuget adapter, but not the vsix.  The number of vsix downloads are very low now, so , yes, we can update it, it doesn't take much, but is it really needed ?  

As mentioned other places, we would really like to see people moving to the nuget adapter, and support for vsix will be deprecated in the VS anyway going forward.

**Comment by n3wjack** [comment] 2019-04-12 13:01
For some reason the nuget adapter isn't always enough. It stopped working for me in 2018 at some point.
Running all tests is OK, but if I want to run a specific test, it doesn't or run them. It can't discover them for some reason according to the output window.
So I resorted to the vsix, which fixed that issue in 2018.
In 2019 I now have the same issue, but no vsix to fix that with. :(

**Comment by bkilada** [comment] 2019-04-14 07:04
Ah, I didn't know there is a NuGet adapter. I tried that but unfortunately ran into similar issues to @n3wjack. I run a test and it immediately fails with no error message. The NUnit 3 NuGet adapter had the same problem, only the NUnit 3 extension worked.

**Comment by n3wjack** [comment] 2019-04-14 12:55
It's a weird problem. In the VS test explorer the tests stay blue as in "not run tests". So the tests are discovered, but when you select one or more, or use the shortcut keys to run the tests in the current open file, the test run starts but doesn't find any tests.
The funny thing is that when you use "run all tests" everything works.

**Comment by OsirisTerje** [comment] 2019-04-14 14:47
Can you upload a small repro?

**Comment by n3wjack** [comment] 2019-04-15 09:15
This behaves the same. It works in VS2017, with the vsix test adapter installed.
In VS2019, it doesn't run the tests, but it does discover them.

I installed the nuget packages in this order:
- nunit 2
- nunit testadapter

[nunit2_testadapter_vs2019.zip](https://github.com/nunit/nunit-vs-adapter/files/3079348/nunit2_testadapter_vs2019.zip)

**Comment by OsirisTerje** [comment] 2019-04-15 11:53
@n3wjack 
1. The vsix doesn't work with VS 2019.  We'll try to get out a new release with that supported shortly. 
2. You have included the nuget adapter, but the vsix takes precendence.  
If you uninstall the vsix, then the nuget adapter should work.
Can you check if all works then?
(3. The discovery you see is probably  not from the adapter, but from the source based real time discovery in the test explorer.  )

**Comment by n3wjack** [comment] 2019-04-15 13:20
I know the VSIX doesn't work in 2019, it's not in the plugin list, which is why I ended up here. :)

I now disabled the VSIX in VS2017 and now I have the same behavior there as in VS2019.
Tests are discovered (you see them in the test explorer), but aren't run when I want to run an individual test or use "Run all".
This is exactly why I installed the VSIX in 2017.

**Comment by OsirisTerje** [comment] 2019-04-15 17:06
@n3wjack Thanks for the repo and the explanations!
I can confirm the bug, a bit surprised about it in fact.  
I'll come back to you on this as soon as possible.  
Thanks again, really appreciate this !

**Comment by n3wjack** [comment] 2019-04-15 17:11
Glad it's reproducible. That makes it a lot easier to fix it.
Good luck!

Op ma 15 apr. 2019 19:06 schreef Terje Sandstrom <notifications@github.com>:

**Comment by OsirisTerje** [comment] 2019-04-15 17:41
UPDATE:
Visual Studio *should* manage to discover the adapters when they are in the packages folder, but it seems there is some change there.  You mention it stopped working "some time" in 2018, and I think that was a minor update change.  

In the options for Test it says:

![image](https://user-images.githubusercontent.com/203432/56151924-b0690200-5fb2-11e9-9eb2-83b8b2a6e9e7.png)

(2) above explains why you get it working with the vsix, which currently doesn't help you with VS2019.
(1) above explains why it don't find it, because the 2.1 adapter doesn't copy itself to the binary output of the test project, which it should do.  

I am pretty sure that before some time in 2018, VS managed to find them under the packages folder, but that doesn't help much now. 

WORKAROUND:
What you can do, is to add a runsettings file:
![image](https://user-images.githubusercontent.com/203432/56153157-caf0aa80-5fb5-11e9-9970-c7108059988a.png)
where you set the adapter path to some local folder where you have manually copied the adapter dll's:
![image](https://user-images.githubusercontent.com/203432/56153295-199e4480-5fb6-11e9-968f-edf7b6978ecc.png)

When I do that with your repo, it starts working again:
![image](https://user-images.githubusercontent.com/203432/56153354-405c7b00-5fb6-11e9-8da2-74f6a53da62e.png)






This is only a workaround, but should work both locally and on a build server.

We need to fix this in the adapter too.
The following can be done:
1)   Update the vsix to support installation in VS2019.  I think we should do this.
2)  Add the copying of the nuget adapter dlls to the test project outputs the same way as it is done in the NUnit3 adapter.  I think we should do this too.

**Comment by dsschnau** [comment] 2019-05-28 21:11
I'm interested in taking on this issue. Is there anyone willing to answer questions about it?

**Closed** 2019-06-03 17:34 UTC
Labels: is:enhancement, pri:high

**Comment by OsirisTerje** [comment] 2019-06-05 13:59
@n3wjack @bkilada The pre-release package for the 2.2 adapter is now available on https://www.myget.org/feed/nunit/package/nuget/NUnitTestAdapter  If you could check it out, it would be awesome.

**Comment by bkilada** [comment] 2019-06-06 08:43
Awesome. No promises but I’ll try if I get a chance.

________________________________

**Comment by OsirisTerje** [comment] 2019-06-06 08:46
@bkilada It is now out on nuget, as version 2.2.0, so it is released :-)  If you find anything, give a ping. :-)

**Comment by n3wjack** [comment] 2019-06-06 14:56
Just upgraded the package in our solution and the unittests are now discovered and run in VS2019.  👍 
Thanks for fixing this!

**Comment by OsirisTerje** [comment] 2019-06-06 17:53
@n3wjack Cool!  Thanks !

**Comment by ValMetcalf** [comment] 2020-04-28 16:45
I still have the exact behaviour as reported by n3wjack.

I'm in Visual Studio 2019 and have the NUnit3TestAdapter (3.16.1) installed. I get the warning NU1701 about that package not being compatible with my project. The tests are dscovered, but not run. Which test adapter should I be using?

**Comment by mikkelbu** [comment] 2020-04-28 19:16
It depends on which version of NUnit framework you are using for your test.

* NUnit3TestAdapter is for NUnit 3
* NUnitTestAdapter is for NUnit 2

**Comment by ValMetcalf** [comment] 2020-04-29 08:43
I am using NUnit3 and NUnit3TestAdapter so I'd expect it to work.

**Comment by mikkelbu** [comment] 2020-04-29 18:41
Ok. So this is not the same problem as n3wjack as the original issue was about NUnit 2 and NUnitTestAdapter. Some questions:
* What is the targetframework of the testproject?
* Do you have real time discovery turned on (in that case does it work if you turn it off) - see image below
* If you turn up the logging level is there any relevant information in Output (if you choose Tests in the dropdown)

![image](https://user-images.githubusercontent.com/1007631/80633829-b0229400-8a59-11ea-9589-5e648a932e33.png)

**Comment by Mykhailo-Seniutovych** [comment] 2020-07-28 09:33
I think it's not fair to stop supporting the extension and impose using NuGet package only. For example, at my team some people use Resharper for running unit tests, some people might use other tools to run the tests. I would like to try to use the NUnitTestAdapter but I don't want to add a NUnitTestAdapter NuGet package to the solution, and "impose" this tool on other people. I think you should provide a tool that can work independently for each individual developer.
