### ISSUE TITLE
Visual Studio Test Explorer ignores [Explicit]

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-vs-adapter#125] opened 2016-07-14 19:51 UTC
@adamralph commented on [Thu Jul 14 2016](https://github.com/nunit/nunit/issues/1664)

When invoking "Run All" in the VS Test Explorer, all tests are run, whether they have `Explicit` or not.

Is this a know problem?

---

@rprouse commented on [Thu Jul 14 2016](https://github.com/nunit/nunit/issues/1664#issuecomment-232661466)

@adamralph this is a known issue that has been reported at nunit/nunit3-vs-adapter#47 if you want to track it there.  Please see that issue for more information.

---

@adamralph commented on [Thu Jul 14 2016](https://github.com/nunit/nunit/issues/1664#issuecomment-232662691)

Thanks @rprouse

**Comment by CharliePoole** [comment] 2016-07-14 19:57
@adamralph Based on discussions elsewhere, it appears that you are using the NUnit VS Test Adatper for NUnit V2. I added some explicit tests to a demo that we run under the V2 adapter and they were reported as Not Run when I clicked Run All.

I also ran the same tests using the NUnit 3 Test Adapter, with the same results. 

Based on that, I'm inclined to close this as non-reproducible. Can you provide any additional info that would help us to see the error you are seeing? Specifically:
 * What software versions are you using?
 * Do you install the adapter using the vsix or the nuget package?
 * Are you using any selection or filtering aside from just clicking Run All?
 * Exactly how are your Explicit tests reported in the IDE?

**Comment by OsirisTerje** [comment] 2016-07-15 20:08
I can reproduce this as follows:
It works correctly when no search filter is given, and Run All is pressed.
![image](https://cloud.githubusercontent.com/assets/203432/16887042/0ed6bb2c-4ad8-11e6-8715-d990d1df3d41.png)

If a search filter is given,  Run All changes in the Test Explorer to mean just those tests that are within the filter, and in that case the explicit test is also run.
![image](https://cloud.githubusercontent.com/assets/203432/16887106/6745cb7c-4ad8-11e6-9b23-9491ed4166a0.png)

I don't think it matters if you use the vsix or the nuget adapter, this is core behaviour in the adapter/test explorer interaction.   
@rprouse :  I haven't checked yet, but you say this work with the NUnit3 adapter?

**Comment by OsirisTerje** [comment] 2016-07-15 20:12
And the behaviour is exactly the same with the NUnit3 adapter.

**Comment by OsirisTerje** [comment] 2016-07-15 20:16
And, I don't think we can easily fix this.  What happens is that Run All without a filter calls the Run method in the adapter with the test assemblies as parameter, and we filter based on that.  When the filter is given, the test explorer sends in a list of tests instead, and we just execute on that list.  The exactly same happens if you just select a test and execute that (or select a set of tests) (right click and Run) .  In the latter case we intend the Explicit test to be run, whereas in the first case we don
't intend  that.  So, we simply don't know what the user is trying to do.   In order to fix this we need more information from the test explorer.

**Comment by CharliePoole** [comment] 2016-07-15 21:15
@OsirisTerje This is the research I've done as well, posted elsewhere because this issue has been kicked from one project to another several times. I was waiting for feedback from @adamralph before closing it, since he has been shuttled around so much already. 

Note that this issue has nothing to do with filters, which is a separate issue we already know about. @rprouse had originally confused it with that issue but @adamralph claims that Explicit tests are not being run when no filter is being used. I can't see that happening and I can't understand how it's possible, so I was ready to close this after he has a chance to comment.

I'll step out of this issue now tha you are handling it.

**Comment by dnperfors** [comment] 2016-07-18 08:59
I get similar behavior as @adamralph, perhaps it is related..

The following screenshot is when I run these tests without a filter, but using the 'Run Tests' from the context menu:
![nunitexplicit](https://cloud.githubusercontent.com/assets/170992/16909891/8dfc3fd6-4cd5-11e6-98c7-2ee1aea6120c.png)

Using 'Run All' gives will ignore the tests.

- Visual Studio 2015 Update 3
- Testadapter via vsix
- Nunit 2.6.4

**Comment by CharliePoole** [comment] 2016-07-18 14:02
"From the context menu" is new information!!! @adamralph is that what you're doing as well?

Somewhat shocking that the two "Run tests" work differently.

**Comment by CharliePoole** [comment] 2016-07-18 14:07
@dnperfors Since Explicit means "only run when directly requested, selecting a test and clicking RunTests should execute them. Run All should not. Seems to be what you are seeing as well as @OsirisTerje and I.

If you right click the category "Passed tests" and run them, VS passes the individual test names to the adapter, exactly as if you had selected each of the tests individually. There's no way for us to distinguish the two cases.

**Comment by adamralph** [comment] 2016-07-18 15:31
I haven't had a chance to fully reproduce, but I believe the problem is that when *any* group of tests is run (as opposed to "Run All"), since *some* filter is present, this is interpreted as being an explicit run of explicit tests.

I believe this behaviour is undesirable. E.g. I most often run all the tests in one project at a time. In this case, I want the explicit tests to be ignored. I just want the rest of the tests in the project. Using "Run All" to avoid running explicit tests isn't really a practical solution.

IMHO the best way to proceed, if possible,  would be to interpret any group of tests as meaning that explicit tests should not be run, and only when an explicitly tests is run in isolation, should that explicit test be run.

**Comment by CharliePoole** [comment] 2016-07-18 16:00
@adamralph I completely agree auto what _should_ happen. That's how the new gui does it.

Unfortunately, the adapter doesn't know anything about the groupings in the IDE. It has an entry point where  VS gives it a list of tests to run, so it runs those tests.

This is actually a different problem from the use of a TFS filter. The only "filter" on the VS side is the list of names from which the adapter creates an nunit filter.

I think you are suggesting that we remove any explicit tests from the list of names unless it's length is 1. That's a bit complicated but possible. However, it sounds even more confusing to users than the current behavior.

**Comment by adamralph** [comment] 2016-07-18 17:11
For me, it's more confusing that when I run all the tests in a given project, the tests marked explicit are being run. It's worse than confusing, it makes the test runner rather unusable. There's no way to run all the tests which are not explicit without running all tests in the solution.

What's more, when using TestDriven.NET and running all tests in a given project, explicit tests are not run, which is the behaviour I desire.

I've pushed a repro solution at https://github.com/adamralph/nunit-vsrunner-explicit-repro

First, change the VS test explorer to group by project. Then right click the project and click "Run Selected Tests". You will see that both the implicit and explicit tests are run.

Next, right click the project in the solution explorer, and click "Run Tests" (the TestDriven.NET menu item). You will see that only the implicit test is run.

TestDriven.NET goes even further. If I right click on the class name in the source code, only the implicit test is executed and not the explicit test.

The behaviour of TestDriven.NET is exactly that which I would expect. If a group of tests (all in a project, all in a class, etc.) are run, only implicit tests are run and explicit tests are ignored.

**Comment by CharliePoole** [comment] 2016-07-18 19:49
Thanks for the repro... I can confirm that what you describe is how the Test Explorer window works. Could you please let us know if this is what you meant all along in filing this issue? You initially referred to "Run All" which has been a source of confusion.

As noted previously, however... this is not our code. It's how the VS IDE works. If we had our own extension to run tests, like TD.Net, then we would no doubt do the same thing. It's what we do in our gui and console runners for example. But in this case, we are an __adapter__ and are limited by the amount of information the IDE passes to us.

As a user, I would be quite disconcerted if I selected two or three test cases and the adapter __failed__ to run one of them because it is Explicit. I would think "Well I selected it, so why didn't it run?"

@OsirisTerje Will have to decide how to treat this issue, but I would say that there is no good solution so we may as well just do what VS tells us to do.

**Comment by dnperfors** [comment] 2016-07-19 06:56
This issue not only happens with the adapter for nunit 2, but also with nunit 3...

**Comment by adamralph** [comment] 2016-07-19 14:53
@CharliePoole so I guess the problem boils down to the fact that the VS runner always gives you a list of individual test cases to run, rather than saying "all in this project", so you can't tell when individual tests have been selected, or some higher level node, like a project?

**Comment by OsirisTerje** [comment] 2016-07-19 16:56
@adamralph :  Yes, you're right.   We're trying to find out if there is any way for us to detect some more information on what the user did.  Currently, afaik, there is none, but we're asking the product group for info on this.

**Comment by CharliePoole** [comment] 2016-07-19 17:07
Exactly.

**Comment by pvlakshm** [comment] 2016-07-20 05:30
Here is my understanding ...
For the repro shown in this thread: 

- If you do a “Run All” then the explicit test is NOT run.
- If you select the test and run, then it is run.
- If you set a Filter to “This” and run, then the filter matches both the tests. And then, the explicit test is run.
- If you select a group and run, then it is run.

This is presently by design. Once you run based on a selection (either by selecting tests, or by specifying a filter, or by selecting a group, etc.) then they get treated as equivalent in terms of “intent” - i.e. of doing some operation (like running them) on all of the tests in that selection; hence that selection of tests is handed off to the adapters.

**Comment by CharliePoole** [comment] 2016-07-20 05:37
Correct, with two clarifications...

1. The design intent is that of the VS folks - the adapter just does as it's told.

2. Filters are a separate matter and are covered by a different issue since we could conceivably do something about how we apply them.

**Comment by adamralph** [comment] 2016-07-20 16:28
I understand the limitations imposed by the VS runner here. Unless there are changes there, I guess there's nothing the NUnit folk can do about this behaviour.

@pvlakshm 

> This is presently by design. Once you run based on a selection (either by selecting tests, or by specifying a filter, or by selecting a group, etc.) then they get treated as equivalent in terms of “intent” - i.e. of doing some operation (like running them) on all of the tests in that selection; hence that selection of tests is handed off to the adapters.

IMHO this is very poor design. Take the example of TestDriven.NET. If I select a grouping which happens to contains an explicit test (e.g. class, project, group of projects), that test is not run, the explicit test is not run, because I haven't explicitly selected it. If, however, I explicitly select it, then it is run. Likewise, if I explicitly selected that test plus some other test, I'd expect both tests two run. The keyword is here is "explicit". Running all tests in a project is not explicitly selecting the explicit test. TestDriven.net displays the behaviour which I expect and believe is correct.

**Comment by CharliePoole** [comment] 2016-07-20 17:15
@adamralph In their defense, I think they were trying to make it "easy" for the adapters/frameworks, which were originally viewed as being fairly simplistic. As I wrote elsewhere, the originators of the Test Window were just emerging from an era where Microsoft guys had to ask management permission to use open source products, and often didn't get it. Then they were suddenly tasked with developing interfaces that would work with a variety of those same open source platforms. They had one model to go by (mstest) so they did the classic "generalization from a single case." I know from discussions with people in Redmond that the general view was that the open source frameworks were probably a lot simpler than mstest but would "obviously" have to work the same way... they were wrong on both counts but by the time the devs I worked with figured that out, there was no chance of convincing the people above them to make changes.

Hmmm... not that great a defense I suppose. :-)

**Comment by CharliePoole** [comment] 2016-07-20 17:23
@pvlakshm To clarify regarding filters... when there is a TFS filter, you don't hand us the selection but the filter itself. We currently take the lazy approach of asking the filter to make the selection, which is why the "Explicit bug" exists for TFS filters.

We could, of course, interpret the filter text ourself, translating it to an NUnit filter with the right semantics. That's what issue nunit/nunit3-vs-adapter#47 is about.

But in the other cases of selections, we have no such out.

**Comment by adamralph** [comment] 2016-07-20 17:50
@CharliePoole WRT to the developers who wrote the code, it's a reasonable defence :wink: 

I don't want to blame people in retrospect for why the test explorer is in it's current state, but equally I'd like the flaws in the current design to be considered irrespective of how that current design came into being.

**Comment by CharliePoole** [comment] 2016-07-20 19:36
@adamralph Unfortunately, the only practical result of considering the flaws here is to acknowledge that we are not in a position to fix them. :-(

**Comment by adamralph** [comment] 2016-07-20 20:13
@CharliePoole yes, it seems so.

Out of interest, do you know how this is handled in other test runners, such as Resharper?

**Comment by CharliePoole** [comment] 2016-07-20 20:16
R# isn't an adapter, but a Visual Studio extension all its own. That means they handle the user interface themselves. I've thought of writing an NUnit extension for VS, but it's not a small undertaking. My priority is on the new nunit gui anyway.

**Comment by adamralph** [comment] 2016-07-20 20:27
@CharliePoole I see. So I guess the bottom line is that there is nothing that can be done without changes to the VS runner. Instead of taking the groupings selected, e.g. class/classes/project/projects, and exploding them into a list of tests and passing that list of tests to the NUnit adapter, it would neee to pass the groupings directly to the NUnit adapter, to it can make a decision to to ignore the explicit tests found within those groupings.

I can we can close this issue and re-raise if those changes are ever made in the VS test runner. Do you know what the best avenue would be to pursue getting this done in the VS test runner?

**Comment by CharliePoole** [comment] 2016-07-21 03:19
I'm not terribly sanguine about getting Microsoft to change this, but you could try one of their user channels. @OsirisTerje can you suggest the best place to go?

**Comment by adamralph** [comment] 2016-07-21 11:21
@CharliePoole I won't hold my breath either :smile: I'm happy to at least raise the issue though.

**Comment by OsirisTerje** [comment] 2016-07-21 14:50
The best is probably to add a uservoice item in the visual studio channel there, and get enough votes.

**Comment by adamralph** [comment] 2016-07-21 15:40
Here we go https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/15312648-pass-intent-rather-than-a-list-of-tests-to-test

I'm not sanguine about the vote count it will gather :wink:

**Comment by CharliePoole** [comment] 2016-07-21 16:01
@OsirisTerje I recommend closing this.

**Comment by OsirisTerje** [comment] 2016-07-22 09:28
Agree

**Closed by OsirisTerje** 2016-07-22 09:28 UTC

**Comment by adamralph** [comment] 2016-07-22 10:46
Thanks for all the info and help guys.
